### PR TITLE
Unit tests for identity service (#5)

### PR DESCRIPTION
**Pull request by eggwhat**

### CODE REVIEW

**Review by SaintAngeLs — APPROVED** [review]
@eggwhat Thank you. Do not forget to  set the var to true
```bash

export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
dotnet test

```

**Comment by eggwhat** [comment]
> @eggwhat Thank you. Do not forget to set the var to true
> 
> ```shell
> export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
> dotnet test
> ```

Should I add this to bash script or directly to test projects csproj?

**Review by an2508374 — APPROVED** [review]

**Comment by SaintAngeLs** [comment]
> > @eggwhat Thank you. Do not forget to set the var to true
> > ```shell
> > export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
> > dotnet test
> > ```
> 
> Should I add this to bash script or directly to test projects csproj?

@eggwhat No, you should't it may cause a collisions with the other projects in the linux environment, I want to make sure that every has the ability to run the test and the projects, still, it seems there is no exclamations about the problems.

**Comment by SaintAngeLs** [comment]
@eggwhat, PLease open the PR to main.

**Pull request merged**
